ministryofjustice/hmpps-manage-prison-visits-orchestration

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
Update ingress host from hmpps to prison to keep in line with other VSIP projects.
> Update ingress host from hmpps to prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/SessionCapacityDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsCapacityTest.kt
VB-1473 - add get sessions capacity endpoint and make a call to visit-scheduler to get a session's capacity details.
> VB-1473 - add get visits sessions capacity endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
VB-1856 - add support for new VSIP endpoint to get session schedules for a prison and date into the orchestration service.
> VB-1856 - add support for new VSIP endpoint to get session schedules

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/OpenApiConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
Change get session schedule parameter to match VSIP and make swagger changes similar to what Aled has done for VSIP.
> Update session schedule date parameters.

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonRegisterClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerContactRegistryApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerOffenderSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/WhereAboutsApiClient.kt
- src/main/resources/application.yml
Updates to values.yaml for each env.
> Updates to env values.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/prison/api/AlertDto.kt
Updates to AlertDto to make comments a nullable value.
> Updates to AlertDto to make comments a nullable value.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionScheduleDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
Add enhanced property to SessionScheduleDto to reflect visit-scheduler changes.
> Add enhanced property to SessionScheduleDto

- .circleci/config.yml
> Updates to circle-ci config to support develop branch.

- src/main/resources/logback-spring.xml
Fix because com.microsoft.applicationinsights.logback.ApplicationInsightsAppender no longer supported
> Logback fix for sb3

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/AuthAwareTokenConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
Updated code to add user-name header to pass the username for logged-in user to the visit-scheduler service
> Updated code to pass logged in user in request header to visit-scheduler service

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/SupportedPrisonsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitByReferenceTest.kt
Get the createdBy, updatedBy and cancelledBy information.
> Vb 1922 retrieve booker details and return as part of get visit end point

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
Update the cancel VSIP endpoint to /v2/cancel
> Vb 2028 create a new v 2 endpoint for cancel visits till syscon migrates cancel over to the new endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/HmppsAuthClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitDetailsClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/hmpps/auth/UserDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/HmppsAuthMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitDetailsByReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitDetailsTest.kt
- src/test/resources/application-test.yml
Get the usernames for a given userid by making a call to the HMPPS Auth service
> Vb 1926 update orchestration service to acquire full username and return it to the UI for each entry

- build.gradle.kts
Update develop with changes to main branch.
> Merge main to develop

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitDetailsClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitHistoryByReferenceTest.kt
VisitHistoryDetails - typo for CANCELLED
https://dsdmoj.atlassian.net/browse/VB-2088
> VB-2088 VisitHistoryDetails - typo for CANCELLED

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitDetailsClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitHistoryByReferenceTest.kt
Update develop with main changes
> Update develop with main changes

- applicationinsights.json
- src/main/resources/logback-spring.xml
make same changes as VSIP to reduce logging on preprod and prod.
> VB-2096 - reduce application logging on Orchestration Prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
- src/main/resources/application.yml
Update downstream webClient for prison API, prisoner offender search API and whereabouts API to use client ID.
> VB-1958 - connect to downstream services using client id.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionScheduleDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
[VB-2217](https://dsdmoj.atlassian.net/browse/VB-2217)
Orchestration Service updates based on visit scheduler DTO changes
[VB-2217]: https://dsdmoj.atlassian.net/browse/VB-2217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Vb 2217 orchestration service updates based on visit scheduler dto

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionScheduleDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
Remove enhanced flag from SessionScheduleDto.
> VB-2225 - remove enhanced flag as no longer used.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/ChangeVisitSlotRequestDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
add sessionTemplateReference to ChangeVisitSlotRequestDto as a fix for VB-2271
> VB-2271 add sessionTemplateReference to ChangeVisitSlotRequestDto.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionDateRangeDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionTimeSlotDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/SessionTemplateFrequency.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
Updates Orchestration API to use N Weekly from visip
> Changes to Orchestration service for changes for - n weekly

- .circleci/config.yml
Changes to circle ci to prevent auto release to dev on develop branch
> Dev approval circel ci

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
remove legacy cancel end points from v si p backend
> Vb 1248 remove legacy cancel end points from v si p backend

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerContactRegistryClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerProfileClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/contact/registry/AddressDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/contact/registry/AddressUsageDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/contact/registry/ContactDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/contact/registry/RestrictionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/contact/registry/TelephoneDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/ContactDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionDateRangeDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/SessionTimeSlotDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitorDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/SessionTemplateFrequency.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonRegisterMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonerContactRegistryMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsScheduleTest.kt
- src/test/resources/application-test.yml
> Merge develope into main v4

- .circleci/config.yml
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/ResourceServerConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/helper/JwtAuthHelper.kt
* VB-2405 - Implementation of suggested workaround to cache jwks key to improve performance.
* add filter for request-dev-approval on build-test-deploy-develop-branch job
> VB-2405 - Implementation of suggested workaround to cache jwks key to improve performance. (#64)

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/CancelVisitOrchestrationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/CancelVisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
[VB-2549](https://dsdmoj.atlassian.net/browse/VB-2549)
Orchestration service - Cancel visit endpoint not working
[VB-2549]: https://dsdmoj.atlassian.net/browse/VB-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Vb 2549 orchestration service cancel not working

- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
Updates to helm values files to allow dev to use IRSA config and leave other environments using old approach.
> VB-2570 DEV-Orchestration service, Update SQS/SNS queue updates IRSA

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PrisonerProfileService.kt
A addition to help us work out if the logs are working
> VB-2578 Added logs to see if app insights is working

- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
New config for IRSA approach, this cannot go live until after hours and CP is gone live.
> VB-2578 PROD - Orchestration service Update SQS/SNS queue updates IRSA

- build.gradle.kts
- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerContactRegistryClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerProfileClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PrisonerProfileService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonerContactRegistryMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
> Merge main into develop v6

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/EventAuditType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitHistoryByReferenceTest.kt
Fix bad spelling on CANCELLED_VISIT
> Fix bad spelling on cancelled visit

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/NonAssociationChangedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/NonAssociationChangedInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/notifiers/PrisonerNonAssociationChangedNotifier.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
JSON was not parsing correctly for additional information odd really because it worked the IT
> Fix for issues on dev with json parsing

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/DomainEvent.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/deserializers/RawJsonDeserializer.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/notifiers/PrisonerNonAssociationChangedNotifier.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsTest.kt
Fix for json errors on dev with non associations version
> Fix for json errors on dev with non associations version

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/notifiers/EventNotifier.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/notifiers/PrisonerNonAssociationChangedNotifier.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsTest.kt
Improved some of the test as the json was not being created properly, this is now fixed plus added some extra checks on the calls
> Refactor of some of the tests, as json was not being parsed correctly

- docker-compose-local.yml
- docker-compose.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
- src/main/resources/application-dev.yml
improved logs for looking at domain events
> Vb 1939 improved logs for looking at domain events

- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/resources/application-dev.yml
added new config for all environments
> Vb 1536 proactively manage bookings, added new config for sqs after moving name space

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PersonRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReceivedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/VisitorRestrictionChangeNotificationDto.kt
Proactively manage bookings, removed json annotations as they were incorrectly added
> Vb 1536 proactively manage bookings, removed json annotations as they were incorrectly added

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PersonRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerRestrictionChangeNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/VisitorRestrictionChangeNotificationDto.kt
Vb 1536 proactively manage bookings, changed json annotations on dates from not blank to not null
> Vb 1536 proactively manage bookings, changed json annotations on dates from not blank to not null

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReceivedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/PrisonerReceivedInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/PrisonerReleasedInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
Vb 1536 proactively manage bookings, added prison code to received and transferred
> Vb 1536 proactively manage bookings, added prison code to received and transferred

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
VB-1536 Proactively manage bookings, refactored logs as we were get too much information in production
> Vb 1536 proactively manage bookings refactored logs

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/DomainEventListenerService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/EventFeatureSwitch.kt
change of logs to reduce logs in production
> Vb 1536 proactively manage bookings, change of logs to reduce logs in production

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/ReleaseReasonType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReleasedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/PrisonerReleasedInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
Prisoner released events are processed, added reason code to release dto
> VB-2760 Prisoner released events are processed, added reason code to  release dto

- README.md
- docker-compose-local.yml
- docker-compose.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-staging.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerProfileClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
- src/test/resources/application-test.yml
Update prisoner-offender-search references to prisoner-search across the project.
> Update prisoner-offender-search references to prisoner-search

- .circleci/config.yml
> Merge main into dev

- .circleci/config.yml
- helm_deploy/hmpps-manage-prison-visits-orchestration/Chart.yaml
merge main into develop with no ff
> merge main into develop with no ff

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitNotificationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/NotificationEventType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/NotificationGroupDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/FutureNotificationVisitGroupsTest.kt
Create Dummy endpoints in VSiP service via orchestration service
> VB-3190 Create Dummy endpoints in VSiP service via orchestration service

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitMinSummaryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitPreviewDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitsByDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitsBySessionTemplateTest.kt
VB-2763 - orchestration service changes for VB-2763 - to get visits by session template reference and date.
> VB-2763 - orchestration service changes for VB-2763 - to get visits by session template reference and date.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationPrisonsConfigController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/GetPrisonTest.kt
added new end point to allow us to get min and max details for a prison
> VB-3238 Add new DTO's and end points to orchestration service.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitPreviewDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitsByDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitsBySessionTemplateTest.kt
- add visitorCount to VisitPreviewDto and set its value.
- uppdate swagger docs.
> VB-2763 - add visitorCount to VisitPreviewDto and set its value.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/PrisonDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/GetPrisonTest.kt
add age config to vsip orchestration service
> VB-3723 add age config to vsip orchestration service

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/BookingRequestDto.kt
> Vb 3728 add server side logic not to delete applications

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationPrisonsConfigController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/PrisonUserClientDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/UserType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/SupportedPrisonsTest.kt
VB-3719 and VB-3718 to allow for PUBLIC and STAFF supported prisons, linked up vsip with orch
> VB-3719 and VB-3718 to allow for PUBLIC and STAFF supported prisons

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/WhereAboutsApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/HmppsAuthMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/ManageUsersApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/MockUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonOffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonRegisterMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonVisitBookerRegistryMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonerContactRegistryMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/WhereaboutsApiMockServer.kt
Initial integration of whereabouts-api into Orchestration Service. Will add further code and tests when the story around whereabouts is further refined and added to the Sprint.
> VB-3824 integrate whereabouts with orchestration service

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/AvailableVisitSessionDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsTest.kt
added sessionTemplateReference to AvailableVisitSessionDto
> added sessionTemplateReference to AvailableVisitSessionDto

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/AvailableVisitSessionDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsTest.kt
Changed visit restriction to session restriction
> changed VisitRestriction to SessionRestriction

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PublicBookerService.kt
small PR for improving log messages
> added extra log message

- .circleci/config.yml
Rework main flow to be exclusive to main, with automatic deployment up to staging.
Introduce feature flow which requires approval and terminates at staging.
> Update circle CI to allow for trunk based feature branch development

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/EventAuditOrchestrationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/VisitHistoryDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/ActionedByDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/UserType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/ManageUsersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitHistoryByReferenceTest.kt
Fixed up visit history because of booker reference change.
> VB-3915 Store booker reference

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicFutureVisitsByBookerReferenceTest.kt
created new endpoint and wired up to Vsip
> VB-3916 Get visits by booker reference

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerReceivedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/PrisonerReceivedInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
Add prisonCode as the visit-scheduler now requires it to flag visits
> Feature: VB-2761 - Prisoner transfer events are processed

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicCancelledVisitsByBookerReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicPastVisitsByBookerReferenceTest.kt
Added cancel end point and past visits also update future visits to have a better name
> added cancelled and past end points

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
Introduce a connection provider with configured max idle times to avoid connections going stale and attempting to be used.
https://dsdmoj.atlassian.net/browse/VB-4274
> VB-4274 - Fix connection reset issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/alerts/api/AlertResponseDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/MockUtils.kt
Encountered a NPE where description field was null, adding nullable ? to field.
> VB-4121 - Replace prison API with Alerts API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/AvailableVisitSessionRestrictionDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerSessionsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsRestrictionTest.kt
Return the restriction type available for a given prisoner and optional list of visitors
https://dsdmoj.atlassian.net/browse/VB-3814
> VB-3814 - New endpoint to get available session restriction

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/ManageUsersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
Instead of showing NOT_KNOWN for public bookers and making calls
to the manage user service when not needed, now we determine what
user type the user is and display the correct full name for them.
Staff -> their full name
Public -> "Public User"
System -> "NOT_KNOWN"
https://dsdmoj.atlassian.net/browse/VB-4521
> Vb 5421 display correct names for needs review page

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerSessionsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionTest.kt
Allows the frontend to retrieve a single visit session and all it's details.
https://dsdmoj.atlassian.net/browse/VB-4528
> VB-4528 - New endpoint to get a single visit session

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonRegisterClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/prison/register/PrisonRegisterContactDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PrisonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonRegisterMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/GetPrisonTest.kt
Add a new call from the prison register client to get a prison's contact details. This will be returned to caller to display to user. If no details are present (404 reponse) then we return empty contact details to caller.
Details returned:
website - String?
phone number - String?
email - String?
https://dsdmoj.atlassian.net/browse/VB-4403
> VB-4403 - Get contact details from prison register

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/CancelVisitOrchestrationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/CancelVisitDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/CancelVisitTest.kt
Fixes bug where public users were being marked as STAFF in event_audit due to missing userType.
> VB-4855 - [BUG] Fix cancelling visits as public user showing as STAFF

- .circleci/config.yml
Added  staff and public playwright tests to the pipeline.
> Add playwright staff e2e tests to pipeline

- .circleci/config.yml
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/MockUtils.kt
This refactor aims at fixing 499 / 500 timeout issues happening in production on the orchestration-service.
> Move to use new hmpps kotlin webclient builder

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/WebClientConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/MockUtils.kt
Attempt to override the connection details for our web clients, to try and fix timeout errors
Background reading
https://dcebotarenco.github.io/posts/reactor-connection-pool/
https://dsdmoj.atlassian.net/browse/VB-5154
> Add custom client connection - Attempt to fix 499 errors

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
Add ROLE_VSIP_ORCHESTRATION_SERVICE__HMPPS_INTEGRATION_API to the /visits/{reference} endpoint
> HMAI-234- hmpps-integration-api - Add role for Get visit information for a Visit by the Reference

- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
Errors appeared after upgrading dps-spring-boot to 7.1.0. This is the fix
> Fix application insights derserialisation errors

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/UpdateVisitTest.kt
Part 1 - Preserve the current functionality and introduce a new endpoint for the frontend UI to call.
Once they have moved over to the new endpoint, part 2 will remove the update flow from the book endpoint and remove the duplicate tests.
https://dsdmoj.atlassian.net/browse/VB-5153
> VB-5153 - Split book and update visit endpoints

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonVisitBookerRegistryClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/OrchestrationExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/PublicBookerController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/booker/registry/RegisterPrisonerForBookerDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/BookerPrisonerRegistrationErrorCodes.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/exception/BookerPrisonerRegistrationException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PublicBookerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/booker/RegisterPermittedPrisonerForBookerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/PrisonVisitBookerRegistryMockServer.kt
Allows a public booker to register a new prisoner. The request will be forwarded to booker-register-api, as this is where all public booker logic belongs.
https://dsdmoj.atlassian.net/browse/VB-4547
> VB-4547 - Booker registers a prisoner endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/PrisonerProfileClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/PrisonerProfileDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisoner/profile/GetPrisonerProfileTest.kt
Move from the UI into the orchestration-service, the retrieval of prisoner restrictions for the prisoner profile.
## JIRA Link
https://dsdmoj.atlassian.net/browse/VB-5352
> VB-5352 - Prisoner restrictions added to prisoner profile

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/VisitStatus.kt
As part of the new request a visit journey, the service needs to handle new statuses.
https://dsdmoj.atlassian.net/browse/VB-5612
> VB-5612 - Add new statues to visit ready for "Request a visit" journey

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationVisitRequestsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/OrchestrationVisitRequestSummaryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitRequestSummaryDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitRequestsForPrisonTest.kt
Calls the new endpoint on visit-scheduler and returns the results.
https://dsdmoj.atlassian.net/browse/VB-5682
> VB-5682 - New endpoint to get visit requests for prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/VisitPreviewDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitsByDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitsBySessionTemplateTest.kt
Update to use VisitPreviewDto as response from visit-scheduler, after changes made to this:
https://github.com/ministryofjustice/visit-scheduler/pull/1121
> Update request response to correct DTO

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/PrisonerScheduledEventDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/ScheduledEventDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/SessionsAndScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/VisitSessionV2Dto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/VisitSessionsAndScheduleDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerSessionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/utils/DateRangeIterator.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsAndScheduleTest.kt
New endpoint to render calendar view.
> VB-5315 GET sessions and schedule endpoint
