ministryofjustice/hmpps-manage-prison-visits-orchestration

- src/main/resources/application.yml
VB-2225 - reduce past visits duration to last 3 months and future visits duration to last 12 months.
> VB-2225 - update config for prisoner profile's past and future visits duration 

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/ApplicationMethodType.kt
Capturing application method type is for requests by visitors. This new `NOT_APPLICABLE` value is for cases where, for example, a visit might be cancelled by the establishment itself.
> VB-2071 Add NOT_APPLICABLE application method type

- .circleci/config.yml
- helm_deploy/hmpps-manage-prison-visits-orchestration/Chart.yaml
- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal`
- The size of the allowlist defined in this file will change: `8 => 0 (8 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist.
The following IPs have been …
> Migrating project to use groups in allowlist

- .trivyignore
- build.gradle.kts
Update dependencies as a fix for security failures.
Update JVM to version 21
> Update dependencies as a fix for security failures.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/application/ApplicationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/application/CreateApplicationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/application/VisitSchedulerCreateApplicationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/ApplicationsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
alter application api to cater for public and staff sources
added some extras into these end points.
```
@Schema(description = "actioned by (Booker reference Or User Name)", example = "asd-asd-asd or AFHETTY_GEN", required = true)
@field:NotBlank
val actionedBy: String,
```
Will need to pass down the Booker Reference in the Public UI and in the Staff the User Name
> Vb 3769 alter application api to cater for public and staff sources

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/BookVisitTest.kt
As part of a rework on the visit-scheduler, the create and update endpoints have been split from their original combined /book endpoint.
To stop the frontend needing to do any extra logic, the orchestration service will figure this out and direct to the right endpoint
> VB-4368 - Move visits event publishing outside of transaction

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PrisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerSessionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/utils/DateUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsDateRangeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/utils/DateUtilsTest.kt
Add 2 parameters which allow you to manually set the opening and closing booking window.
fromDateOverride is an Int which is used to offset from todays date, the opening booking window.
toDateOverride is an Int which is used to offset from todays date, the closing booking window.
E.g.
fromDateOverride = 2 and toDateOverride = 28, would give a booking window of (Opening = today + 2, Closing = today + 28).
Note: These are optional overrides. If not passed in, the prison config min and max will be used instead.
https://dsdmoj.atlassian.net/browse/VB-4507
> VB-4507 - Allow the overriding of the opening and closing booking window for public and pvb services

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/PrisonDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/prison/register/PrisonRegisterContactDetailsDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/prisons/GetPrisonTest.kt
Prison register returns a prison web address as `webAddress`, not `website`.
Fix this and update property name in `PrisonDto` to match.
> VB-4403 Fix prison web address returned with PrisonDto

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/builder/OrchestrationVisitDtoBuilder.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/OrchestrationVisitDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/PrisonerSearchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicCancelledVisitsByBookerReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicFutureVisitsByBookerReferenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/PublicPastVisitsByBookerReferenceTest.kt
As requested by frontend, we need to display the prisoner name for each visit. Adding call to get prisoner details and capturing the name on the returned dto.
Updated integration tests to cover new call to prisoner search.
> VB-4757 - Add prisoner name to orchestration visit dto

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/ContactDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/VisitByReferenceTest.kt
Introduce the ability for a public booker to provide an email address for the visit main contact.
> VB-4331 - Public booker can provide email address for main contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/BookingOrchestrationRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/BookingRequestDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/BookVisitTest.kt
Adds the "userType" to the bookingRequestDto, to allow us to identify easily what user type is making the update for the booking.
https://dsdmoj.atlassian.net/browse/VB-4943
> Vb 4943 fix incorrect user type

- build.gradle.kts
Remove springdoc-openapi-starter-webmvc-api and springdoc-openapi-starter-webmvc-common as they are not needed - refer - https://github.com/springdoc/springdoc-openapi/ and revert webmvc-ui to 2.7.0
> revert webmvc-ui to 2.7.0

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/OrchestrationPrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/enums/NotificationEventAttributeType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PrisonerVisitsNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/VisitNotificationEventAttributeDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/FutureNotificationVisitGroupsTest.kt
This PR introduces "attributes" to the visit event notifications. These attributes allow for extra information to be captured for specific event types. Currently only 3 events (VISITOR_RESTRICTION_UPSERTED_EVENT, PERSON_RESTRICTION_UPSERTED_EVENT, VISITOR_UNAPPROVED_EVENT) have extra fields, but this new design allows new fields (attributes) to be added dynamically to the new attributes table with little changes required to the code itself.
https://dsdmoj.atlassian.net/browse/VB-4411
https://dsdmoj.atlassian.net/browse/VB-5040
> VB-4411 - Feature - Visit booking details page rework

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/BookerPrisonerInfoClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/BookerPrisonerInfoDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/booker/GetPermittedPrisonersForBookerTest.kt
This will be used by the frontend to determine if the service should allow Remand prisoners with no VO balance to book freely (as remand prisoners don't require VOs, they're not convicted).
https://dsdmoj.atlassian.net/browse/VB-5053
> VB-5053 - Add convicted status to the booker prisoner info

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/BookerPrisonerInfoDto.kt
Add correct type to `convictedStatus` so it is usable by TypeScript in front-end.
> VB-5053 Correctly type convictedStatus

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitBookingDetailsClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/orchestration/VisitBookingDetailsDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/ContactDto.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/visit/GetVisitBookingDetailsTest.kt
Add `visitContactId` to `visitContact` in `VisitBookingDetailsDto`. This is the `nomisPersonId` of the visitor set as the `visitContact` (i.e. main contact).
This is needed so that `VisitBookingDetailsDto` has all the required information to initiate an update visit journey.
> VB-5215 Add contact ID for visit's main contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
Errors were being caught and logged but not then rethrown so I think this was resulting in the tasks not ending up on the DLQ
> Fix issue where VisitCreated and VisitUpdated errors would not end up the DLQ

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/client/VisitSchedulerClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/controller/OrchestrationSessionsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/VisitSchedulerSessionsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/mock/VisitSchedulerMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsDateRangeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsWithAppointmentsCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsWithoutAppointmentsCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/VisitSessionsTest.kt
VB-4095 and VB-4096 changes to add userType parameter to get visit sessions and get available visit sessions API calls.
> Add userType parameter to get visit sessions and get available visit sessions API calls.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/PersonRestrictionUpsertedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/visitnotification/VisitorRestrictionUpsertedNotificationDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/PersonRestrictionUpsertedInfo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/service/listeners/events/additionalinfo/VisitorRestrictionUpsertedInfo.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/domainevents/PrisonVisitsEventsSqsTest.kt
This will be used in the visit-scheduler to capture the restriction ID, the frontend will use it to highlight a specific restriction on booking details page.
> Add restriction ID to visitor local and global restriction events

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/utils/DateUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/integration/sessions/AvailableVisitSessionsDateRangeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/utils/DateUtilsTest.kt
VB-5607 - use prison config if fromDateOverride and toDateOverride passed is less than or more than configured limit.
> VB-5607 - Use prison config when fromDateOverride and toDateOverride are below / above prison config limits.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/PrisonerScheduledEventDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/dto/visit/scheduler/sessions/VisitSessionV2Dto.kt
* PrisonerScheduledEventDto
* swap one of the properties returned
* remove eventDate - redundant as it is contained in SessionsAndScheduleDto, which has the date
* VisitSessionV2Dto
* flatten structure so startTime / endTime are at top level
> VB-5315 Tweak visit session and schedule DTOs

- helm_deploy/hmpps-manage-prison-visits-orchestration/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsmanageprisonvisitsorchestration/config/ResourceServerConfiguration.kt
Needed to allow the endpoint to be called from within k8s without requiring auth
> Fix retryDlq failing
